src/AppSistema/Entity/Enlace.php
<?php

namespace AppSistema\Entity;

use AppSistema\Repository\SistemaEnlaceRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SistemaEnlaceRepository::class)
 */
class Enlace
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    public function getId(): ?int
    {
        return $this->id;
    }
}

src/AppSistema/Entity/Evento.php
<?php

namespace AppSistema\Entity;

use App\Entity\BaseEntity;
use AppSistema\Repository\EventoRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EventoRepository::class)
 */
class Evento extends BaseEntity
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $descripcion;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $origen;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nivel;

    /**
     * @ORM\Column(type="datetime")
     */
    private $registradoEn;

    public function __construct($nivel, $origen, $registradoPor, $descripcion, $tipo, $informacionExtra = '')
    {
        $this->descripcion = $descripcion;
        $this->nivel = $nivel;
        $this->origen = $origen;
        $this->registradoPor = $registradoPor;
        $this->registradoEn = new \DateTime();
        $this->tipo = $tipo;
        $this->informacionExtra = $informacionExtra;
    }

    /**
     * @ORM\ManyToOne(targetEntity=Usuario::class, inversedBy="eventos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $registradoPor;

    /**
     * @ORM\Column(type="integer", nullable=false)
     */
    private $tipo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $informacionExtra;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescripcion(): ?string
    {
        return $this->descripcion;
    }

    public function setDescripcion(string $descripcion): self
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    public function getOrigen(): ?string
    {
        return $this->origen;
    }

    public function setOrigen(string $origen): self
    {
        $this->origen = $origen;

        return $this;
    }

    public function getNivel(): ?string
    {
        return $this->nivel;
    }

    public function setNivel(string $nivel): self
    {
        $this->nivel = $nivel;

        return $this;
    }

    public function getRegistradoEn(): ?\DateTimeInterface
    {
        return $this->registradoEn;
    }

    public function setRegistradoEn(\DateTimeInterface $registradoEn): self
    {
        $this->registradoEn = $registradoEn;

        return $this;
    }

    public function getRegistradoPor(): ?Usuario
    {
        return $this->registradoPor;
    }

    public function setRegistradoPor(?Usuario $registradoPor): self
    {
        $this->registradoPor = $registradoPor;

        return $this;
    }

    public function getTipo(): ?string
    {
        switch ($this->tipo){
            case 0: return 'No especificado'; break;
            case 1: return 'Registar entidad'; break;
            case 2: return 'Modificar entidad'; break;
            case 3: return 'Eliminar entidad'; break;
            case 4: return 'Excepción del sistema'; break;
            case 5: return 'Inicio de sesión'; break;
            case 6: return 'Cierre de sesión'; break;
            case 7: return 'Error del sistema'; break;
            default: return 'No especificado'; break;
        }
    }

    public function setTipo(?int $tipo): self
    {
        $this->tipo = $tipo;

        return $this;
    }

    public function toJson(){
        $attributes = [
            'id',
            'registradoEn',
            'registradoPor'
        ];
        return $this->toJsonAttributes($attributes);
    }

    public function getInformacionExtra(): ?string
    {
        return $this->informacionExtra;
    }

    public function setInformacionExtra(?string $informacionExtra): self
    {
        $this->informacionExtra = $informacionExtra;

        return $this;
    }
}

src/AppSistema/Entity/Usuario.php
<?php

namespace AppSistema\Entity;

use App\Entity\BaseEntity;
use AppSistema\Repository\UsuarioRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Ignore;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=UsuarioRepository::class)
 * @Vich\Uploadable
 */
class Usuario extends BaseEntity implements UserInterface, PasswordAuthenticatedUserInterface
{

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nombres;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $apellidos;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cargo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $foto;

    /**
     * @Vich\UploadableField(mapping="usuario_foto", fileNameProperty="foto")
     * @Ignore()
     * @var File
     */
    private $fotoFile;

    /**
     * @ORM\Column(type="datetime")
     */
    private $creadoEn;

    /**
     * @ORM\Column(type="datetime")
     */
    private $actualizadoEn;


    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $activo;

    /**
     * @ORM\OneToMany(targetEntity=Evento::class, mappedBy="registradoPor")
     */
    private $eventos;

    public function __construct()
    {
        $this->activo = true;
        $this->eventos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        if(!$roles){
            $roles[] = 'ROLE_';
        }
        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNombres(): ?string
    {
        return $this->nombres;
    }

    public function setNombres(string $nombres): self
    {
        $this->nombres = $nombres;

        return $this;
    }

    public function getApellidos(): ?string
    {
        return $this->apellidos;
    }

    public function setApellidos(?string $apellidos): self
    {
        $this->apellidos = $apellidos;

        return $this;
    }

    public function getCargo(): ?string
    {
        return $this->cargo;
    }

    public function setCargo(?string $cargo): self
    {
        $this->cargo = $cargo;

        return $this;
    }

    public function getNombreCompleto(){
        $nombre_completo = $this->nombres;
        $nombre_completo .= $this->apellidos ? " " . $this->apellidos : '';

        return $nombre_completo;
    }

    public function getFoto(): ?string
    {
        return $this->foto;
    }

    public function setFoto(?string $foto): self
    {
        $this->foto = $foto;

        return $this;
    }

    public function isActivo(): ?bool
    {
        return $this->activo;
    }

    public function setActivo(?bool $activo): self
    {
        $this->activo = $activo;

        return $this;
    }

    /**
     * @return File
     */
    public function getFotoFile(): ?File
    {
        return $this->fotoFile;
    }

    public function getCreadoEn(): ?\DateTimeInterface
    {
        return $this->creadoEn;
    }

    public function setCreadoEn(\DateTimeInterface $creadoEn): self
    {
        $this->creadoEn = $creadoEn;

        return $this;
    }

    public function getActualizadoEn(): ?\DateTimeInterface
    {
        return $this->actualizadoEn;
    }

    public function setActualizadoEn(\DateTimeInterface $actualizadoEn): self
    {
        $this->actualizadoEn = $actualizadoEn;

        return $this;
    }

    /**
     * @param File $fotoFile
     */
    public function setFotoFile(File $fotoFile = null): void
    {
        $this->fotoFile = $fotoFile;
        if ($fotoFile) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->actualizadoEn = new \DateTime();
        }
    }

    public function getEventos(): Collection
    {
        return $this->eventos;
    }

    public function addEvento(Evento $evento): self
    {
        if (!$this->eventos->contains($evento)) {
            $this->eventos[] = $evento;
            $evento->setRegistradoPor($this);
        }

        return $this;
    }

    public function removeEvento(Evento $evento): self
    {
        if ($this->eventos->removeElement($evento)) {
            // set the owning side to null (unless already changed)
            if ($evento->getRegistradoPor() === $this) {
                $evento->setRegistradoPor(null);
            }
        }

        return $this;
    }

    public function toJson(){
        $attributes = [
            'id',
            'creadoEn',
            'actualizadoEn',
            'creadoPor',
            'actualizadoPor'
        ];
        return $this->toJsonAttributes($attributes);
    }

}

src/AppSistema/Form/RolType.php
<?php

namespace AppSistema\Form;

use AppSistema\Entity\Rol;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RolType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('identificador', TextType::class, [
                'attr' => [
                    'class' => 'metro-input',
                    'readonly' => true
                ]
            ])
            ->add('nombre', TextType::class, [
                'attr' => [
                    'class' => 'metro-input',
                    'data-validate' => 'required'
                ]
            ])
            ->add('descripcion', TextType::class, [
                'label' => 'Descripción',
                'attr' => [
                    'class' => 'metro-input',
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Rol::class,
        ]);
    }
}

src/AppSistema/Controller/EventoController.php
<?php

namespace AppSistema\Controller;

use AppSistema\Repository\EventoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class EventoController extends AbstractController
{
    /**
     * @Route("/sistema/registros/eventos", name="app_sistema_registros_eventos")
     */
    public function index(EventoRepository $eventoRepository): Response
    {
        return $this->render('sistema_evento/index.html.twig', [
            'eventos' => $eventoRepository->findBy([], ['registradoEn' => 'DESC']),
        ]);
    }
}

src/AppSistema/Controller/ModuloController.php
<?php

namespace AppSistema\Controller;

use AppSistema\Entity\SistemaModulo;
use AppSistema\Repository\SistemaModuloRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ModuloController extends AbstractController
{
    /**
     * @Route("/modulo/{id}", name="app_sistema_modulo_show")
     */
    public function show(SistemaModuloRepository $sistemaModuloRepository, string $id): Response
    {
        $modulo = $sistemaModuloRepository->findOneByIdentificador($id);
//        dd($modulo);
        return $this->redirectToRoute(
            sprintf('app_mod_%s_dashboard', $modulo->getIdentificador())
        );
    }

    /**
     * @Route("/install/module/activation", name="app_sistema_modulo_activation")
     */
    public function activate(EntityManagerInterface $entityManager, Request $request): Response
    {
        $modulos = $entityManager->getRepository(SistemaModulo::class)->findAll();
        if($request->getMethod() === 'POST'){
            $data = $request->request->all();
            foreach ($data as $module_id => $value){
                $module = $entityManager->getRepository(SistemaModulo::class)->findOneByIdentificador($module_id);
                $module->setActivado(true);
                $entityManager->getRepository(SistemaModulo::class)->add($module, true);
            }
            $this->notificacionSatisfactoria('Módulos activados satisfactoriamente. Inicie sesión');
            return $this->redirectToRoute('app_security_login');
        }

        return $this->renderForm('app/security/module_activation.html.twig', [
            'modulos' => $modulos,
        ]);
    }


}

src/AppSistema/Controller/RolController.php
<?php

namespace AppSistema\Controller;

use App\Controller\AppController;
use AppSistema\Entity\Rol;
use AppSistema\Form\RolType;
use AppSistema\Repository\RolRepository;
use Doctrine\DBAL\Exception\UniqueConstraintViolationException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/rol")
 */
class RolController extends AppController
{
    /**
     * @Route("/", name="app_rol_index", methods={"GET"})
     */
    public function index(RolRepository $rolRepository): Response
    {
        return $this->render('rol/index.html.twig', [
            'rols' => $rolRepository->findAll(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_rol_show", methods={"GET"})
     */
    public function show(Rol $rol): Response
    {
        return $this->render('rol/show.html.twig', [
            'rol' => $rol,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_rol_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Rol $rol, RolRepository $rolRepository): Response
    {
        $form = $this->createForm(RolType::class, $rol);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($form->isSubmitted() && $form->isValid()) {
                try{
                    $rolRepository->add($rol, true);
                    $this->notificacionSatisfactoria('Datos del rol modificados satisfactoriamente');
                    /** EVENTO **/
                    $this->registrarEventoSistema('Información', get_class($this), $this->getUser(), 'El rol ' . $rol->getIdentificador() . 'ha sido modificado', 2);
                    /*********/
                } catch (UniqueConstraintViolationException $e){
                    $this->notificacionError('Ya existe un rol con el nombre ' . $rol->getNombre());
                    $this->notificacionExcepcion($e->getMessage());
                    /** EVENTO **/
                    $this->registrarEventoSistema('Error', get_class($this), $this->getUser(), $e->getMessage(), 2);
                    /*********/
                } catch (\Exception $ex){
                    $this->notificacionErrorInesperado();
                    $this->notificacionExcepcion($ex->getMessage());
                    /** EVENTO **/
                    $this->registrarEventoSistema('Error', get_class($this), $this->getUser(), $ex->getMessage(), 4);
                    /*********/
                }

                return $this->redirectToRoute('app_rol_index', [], Response::HTTP_SEE_OTHER);
            }
        }

        return $this->renderForm('rol/new.html.twig', [
            'rol' => $rol,
            'form' => $form,
        ]);
    }
}

templates/app_sistema/usuario/index.html.twig
{% extends '_themes/metroui/base.html.twig' %}

{% block title %}Usuarios{% endblock %}

{% block content %}
    <div class="d-flex flex-align-center p-2 bg-white mb-3">
        <span class="ml-2 text-leader">Usuarios</span>
        {% if is_granted('ROLE_ESPECIALISTA_PRINCIPAL') %}
            <div class="ml-auto">
                <a class="button primary flex-self-center" href="{{ path('app_usuario_new') }}" title="Nuevo usuario">
                    <span class="mif-add"></span>
                </a>
            </div>
        {% endif %}
    </div>

    <div class="bg-white p-3">
        <table class="table no-check">
            <thead>
            <tr>
                <th>Avatar</th>
                <th>Identificador</th>
                <th>Nombre(s) y apellidos</th>
                <th>Cargo</th>
                <th>Roles</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for usuario in usuarios %}
                <tr>
                    <td>
                        <div style="width: 32px;">
                            {% if usuario and usuario.foto %}
                                <img class="avatar" src="{{ asset(vich_uploader_asset(usuario, 'fotoFile')) }}">
                            {% else %}
                                <img class="avatar" src="{{ asset('assets/images/usuarios/generic_metroui.jpg') }}">
                            {% endif %}
                        </div>
                    </td>
                    <td>{{ usuario.userIdentifier }}</td>
                    <td>{{ usuario.nombreCompleto }}</td>
                    <td>{{ usuario.cargo }}</td>
                    <td>
                        {% for rol in usuario.roles %}
                            <code class="primary">{{ rol | rol_nombre }}</code>
                        {% endfor %}
                    </td>
                    <td>

                        <div class="toolbar float-right">
                            <a title="Mostrar" class="tool-button primary" href="{{ path('app_usuario_show', {'id': usuario.id}) }}">
                                <span class="mif-eye"></span>
                            </a>
                            {% if is_granted('ROLE_ESPECIALISTA_PRINCIPAL') %}
                                <a title="Editar" class="tool-button secondary" href="{{ path('app_usuario_edit', {'id': usuario.id}) }}">
                                    <span class="mif-pencil"></span>
                                </a>
                                <a title="Cambiar contraseña" class="tool-button warning" href="{{ path('app_usuario_change_password', {'id': usuario.id}) }}">
                                    <span class="mif-key"></span>
                                </a>
                                {% if usuario.activo %}
                                    <form method="post" action="{{ path('app_usuario_delete', {'id': usuario.id}) }}" onsubmit="return confirm('¿Está seguro que desea eliminar el usuario?');">
                                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ usuario.id) }}">
                                        <button title="Eliminar" class="tool-button alert">
                                            <span class="mif-bin"></span>
                                        </button>
                                    </form>
                                {% else %}
                                    <a title="Habilitar" class="tool-button success" href="{{ path('app_usuario_habilitar', {'id': usuario.id}) }}">
                                        <span class="mif-checkmark"></span>
                                    </a>
                                {% endif %}
                            {% endif %}
                        </div>

                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/app_sistema/usuario/new.html.twig
{% extends '_themes/metroui/base.html.twig' %}

{% set title = app.request.get('_route') | get_action ~ ' usuario' %}

{% if app.request.get('_route') == 'app_usuario_change_password' and app.user == usuario %}
    {% set title = 'Cambiar mi contraseña' %}
{% endif %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    {{ form_start(form, { 'attr' : { 'data-role': 'validator' } }) }}
    <div class="d-flex flex-align-center p-2 bg-white mb-3">
        <a href="{{ path('app_usuario_index') }}" class="button square outline"><span class="mif-arrow-left"></span></a>
        <span class="ml-2 text-leader">{{ title }}
            {% if app.request.get('_route') != 'app_usuario_new' and title != 'Cambiar mi contraseña' %}
            <span class="text-bold">
                {{ usuario.userIdentifier }}
            </span>
            {% endif %}
        </span>
        <div class="ml-auto">
            <button type="submit" title="Guardar" class="button square primary"><span class="mif-checkmark"></span></button>
        </div>

    </div>
    {% if app.request.get('_route') != 'app_usuario_change_password' %}
        <div class="bg-white p-3">
            <div class="row">
                <div class="cell-md-3">
                    {{ form_row(form.username) }}
                </div>
                <div class="cell-md-3">

                </div>
                {% if form.password is defined %}
                <div class="cell-md-3">
                    {{ form_row(form.password) }}
                </div>
                <div class="cell-md-3">
                    {{ form_row(form.confirm_password) }}
                </div>
                {% endif %}
            </div>
{#            {% if app.user != usuario %}#}
            <div class="row">
                <div class="cell-md-12">
                    {{ form_row(form.fotoFile) }}
                </div>
            </div>
{#            {% endif %}#}
            <div class="row">
                <div class="cell-md-6">
                    {{ form_row(form.activo) }}
                </div>
            </div>
            <div class="row">
                <div class="cell-md-12">
                    {{ form_row(form.roles) }}
                </div>
            </div>
            <div class="row">
                <div class="cell-md-4">
                    {{ form_row(form.nombres) }}
                </div>
                <div class="cell-md-4">
                    {{ form_row(form.apellidos) }}
                </div>
                <div class="cell-md-4">
                    {{ form_row(form.cargo) }}
                </div>
            </div>
        </div>
    {% else %}
        <div class="bg-white p-3">
            <div class="row">
                {% if form.password is defined %}
                    <div class="cell-md-3">
                        {{ form_row(form.password) }}
                    </div>
                    <div class="cell-md-3">
                        {{ form_row(form.confirm_password) }}
                    </div>
                {% endif %}
            </div>
        </div>
    {% endif %}
    {{ form_row(form._token) }}
    {{ form_end(form, {'render_rest' : false }) }}
{% endblock %}

templates/app_sistema/usuario/show.html.twig
{% extends '_themes/metroui/base.html.twig' %}

{% block title %}Perfil de usuario{% endblock %}

{% block content %}
    <div class="d-flex flex-align-center p-2 bg-white mb-3">
        <a href="{{ path('app_usuario_index') }}" class="button square outline"><span class="mif-arrow-left"></span></a>
        <span class="ml-2 text-leader">Perfil de usuario <span class="text-bold">{{ usuario.userIdentifier }}</span></span>
        {% if is_granted('ROLE_ESPECIALISTA_PRINCIPAL') %}
        <div class="ml-auto">
            <a title="Nuevo" href="{{ path('app_usuario_new') }}" class="button square primary"><span class="mif-add"></span></a>
            <a title="Editar" href="{{ path('app_usuario_edit', {'id' : usuario.id }) }}" class="button square secondary"><span class="mif-pencil"></span></a>
            <a title="Cambiar contraseña" href="{{ path('app_usuario_change_password', {'id': usuario.id}) }}" class="button square warning">
                <span class="mif-key"></span>
            </a>
            {% if not usuario.activo %}
                <a title="Habilitar" href="{{ path('app_usuario_habilitar', {'id': usuario.id}) }}" class="button square success">
                    <span class="mif-checkmark"></span>
                </a>
            {% else %}
                <form class="ml-1 float-right" method="post" action="{{ path('app_usuario_delete', {'id': usuario.id}) }}" onsubmit="return confirm('¿Está seguro que desea eliminar el usuario?');">
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ usuario.id) }}">
                    <button title="Eliminar" class="button alert">
                        <span class="mif-bin"></span>
                    </button>
                </form>
            {% endif %}
        </div>
        {% endif %}
    </div>

    <div class="d-flex flex-align-center p-2 bg-white mb-3">
        <div class="w-100">
            {{ form_start(form) }}
            {{ form_row(form.usuario) }}
            {{ form_end(form) }}
        </div>
        <script>
            function submit_form() {
                $('form[name="form"]').submit();
            }
        </script>
    </div>

    <div class="skill-box">
        <div class="header border-top border-bottom bd-default">
            {% if usuario and usuario.foto %}
                <img class="avatar" src="{{ asset(vich_uploader_asset(usuario, 'fotoFile')) }}">
            {% else %}
                <img class="avatar" src="{{ asset('assets/images/usuarios/generic_metroui.jpg') }}">
            {% endif %}
            <div class="title">{{ usuario.nombreCompleto }}</div>
            <div class="subtitle">{{ usuario.cargo }}</div>
        </div>
        <div class="p-6">
            <div class="text-bold">Estado</div>
            {% if usuario.activo %}
                <code class="success">Activo</code>
            {% else %}
                <code class="alert">Inactivo</code>
            {% endif %}
        </div>
        <div class="p-6">
            <div class="text-bold">Roles</div>
            {% for rol in usuario.roles %}
                <code class="primary">{{ rol | rol_nombre }}</code>
            {% endfor %}
        </div>

    </div>

{% endblock %}